name: phd_assignment
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - omegaconf=2.2.3
  - python=3.9
  - pytorch
  - cudatoolkit=11.3
  - pytorch-lightning=1.7.7
  - torchvision=0.13.1
  - wandb=0.13.4
  - matplotlib
  - seaborn
  - numpy
  - click
  - pandas
  - tqdm
  - scipy
  - scikit-learn
