seed: 12345
optimize:
  optimizer: Adam
  lr: 0.001
  weight_decay: 0
train:
  method: Finetune
  model: LeNet
  epochs: 10
  batch_size: 64
  loss: MSE
  use_reg: False
  save_dir: ../models
dataset:
  name: STL10
  channels: 3
  is_corrupted: False
  root: ../data
  num_workers: 4
  use_collate: False
wandb:
  log: True
  dir: ../wandb
  experiment_name: 'ae_mse'
  entity: 'sayak_delft'
  project: 'phd_assign'